defaults:
  - env: simenv
  - gflownet: trajectorybalance
  - loss: trajectorybalance
  - policy: multihead_greenhouse
  - proxy: cropSimulation_cvar_mean
  - logger: wandb_artifact
  - user: default
  - evaluator: base
  - buffer: base
  - _self_

device: cpu
float_precision: 32
n_samples: 100
seed: 0

policy:
  backward:
    type: fixed
    fixed_output: [0.0]

optimizer:
  forward: 32
  backward_replay: 0

env:
  precomputed: False
  step_fraction: 0.3
  n_cycles: 2

gflownet:
  optimizer:
    n_train_steps: 5000
    lr_z_mult: 10

proxy:
  loss_norm: q10q90
  q_low: 0.10
  q_high: 0.90
  reward_cache_path: precomputed_cvar/reward_table_sf0.3.json

hydra:
  run:
    dir: ${user.logdir.root}/${oc.env:SLURM_JOB_ID,local}/${now:%Y-%m-%d_%H-%M-%S_%f}
  sweep:
    dir: ${user.logdir.root}/${oc.env:SLURM_JOB_ID,local}/multirun/${now:%Y-%m-%d_%H-%M-%S_%f}
  job:
    chdir: False
  sweeper:
    params:
      seed: 0, 1
      gflownet.optimizer.lr: 5e-4
      gflownet.random_action_prob: 0.0
      proxy.beta: 2, 4, 8
      proxy.context_tail_count: 2
      proxy.context_cvar_lambda: 0.25
